# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel  
  
os:
  - linux
  #- osx   # build of osx is extremely slow, disabled

matrix:
  exclude:
  - r: devel
    os: osx
    
